services:
  - type: web
    name: nova-haidong-quiz-v2
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: GH_REPO
        value: FGboss/nova-haidong-quiz-v2