// 技术进阶 - 全系列产品综合考核 - 题库
// 基于知识库：诺瓦+嗨动全部产品系列的综合交叉考核
const QUESTIONS_tech_comprehensive = [
  // ===== 单选题 (10题/套，题库~30题) =====
  { id: 'tcz_s1', type: 'single', question: '在诺瓦LED控制系统中，发送卡的标准带载能力是多少像素？', options: ['130万像素', '65万像素', '260万像素', '520万像素'], answer: 'A', points: 5, explain: '诺瓦发送卡标准带载能力为130万像素，超过此数量需要增加发送卡或使用多网口方案。' },
  { id: 'tcz_s2', type: 'single', question: '嗨动B系列拼接处理器属于什么类型的产品？', options: ['专业级多屏拼接处理器', 'LED接收卡', '音频处理器', '中控系统'], answer: 'A', points: 5, explain: 'B系列是嗨动专业级多屏拼接处理器，支持多路输入输出和画面拼接。' },
  { id: 'tcz_s3', type: 'single', question: '分布式系统中，编码器的主要功能是什么？', options: ['将音视频信号编码为IP网络流', '解码网络流为显示信号', '放大信号', '存储信号'], answer: 'A', points: 5, explain: '编码器将音视频信号编码为IP网络数据流，通过标准网络传输到解码器。' },
  { id: 'tcz_s4', type: 'single', question: '天韵系列音频产品属于哪个品牌？', options: ['嗨动(Hidong)', '诺瓦(NovaStar)', '科赛', '灵曜'], answer: 'A', points: 5, explain: '天韵系列是嗨动品牌的专业扩声系统产品线。' },
  { id: 'tcz_s5', type: 'single', question: 'LED一体机与传统拼接LED屏幕最大的区别是什么？', options: ['高度集成，即插即用，无需额外配置', '价格更低', '亮度更高', '尺寸更大'], answer: 'A', points: 5, explain: 'LED一体机将控制系统集成在内部，实现即插即用，无需分别配置发送卡和接收卡。' },
  { id: 'tcz_s6', type: 'single', question: '无缝混插矩阵的"无缝切换"功能主要解决什么问题？', options: ['信号切换时画面无黑屏、无闪烁', '机箱接口松动', '信号衰减', '色彩失真'], answer: 'A', points: 5, explain: '无缝切换通过帧同步技术，确保信号切换时画面无黑屏、无闪烁，适用于广电和直播场景。' },
  { id: 'tcz_s7', type: 'single', question: 'ECS3000智能中控系统属于哪个品牌？', options: ['嗨动(Hidong)', '诺瓦(NovaStar)', '艾欧塔', '科赛'], answer: 'A', points: 5, explain: 'ECS3000是嗨动品牌的旗舰级智能中控系统。' },
  { id: 'tcz_s8', type: 'single', question: 'Dante音频网络协议基于什么类型的网络？', options: ['标准IP网络', '专用音频网络', '模拟网络', '光纤专网'], answer: 'A', points: 5, explain: 'Dante基于标准IP网络，使用标准网络交换机和布线，实现低延迟多通道数字音频传输。' },
  { id: 'tcz_s9', type: 'single', question: '缪斯播控系统的主要功能是什么？', options: ['集中管理和播放多路音视频内容', '控制LED屏幕亮度', '处理音频信号', '管理网络设备'], answer: 'A', points: 5, explain: '缪斯是多媒体内容管理和播放平台，可集中管理、排程和播放多路音视频内容。' },
  { id: 'tcz_s10', type: 'single', question: '阿丽塔LED拼控的核心优势是什么？', options: ['集成发送卡和接收卡功能，直接驱动LED模组', '支持更多输入接口', '价格更低', '体积更小'], answer: 'A', points: 5, explain: '阿丽塔将发送卡和接收卡功能集成，直接驱动LED模组，简化系统架构。' },
  { id: 'tcz_s11', type: 'single', question: '诺瓦V系列视频处理器的定位是什么？', options: ['高端旗舰级视频拼接处理器', '入门级产品', '中端产品', '配件产品'], answer: 'A', points: 5, explain: 'V系列是诺瓦的高端旗舰级视频拼接处理器，面向大型LED显示项目和高端应用场景。' },
  { id: 'tcz_s12', type: 'single', question: '西格玛双引擎分布式系统的"双引擎"指的是什么？', options: ['浅压缩和深压缩两种编码引擎', '双CPU处理', '双电源冗余', '双网络接口'], answer: 'A', points: 5, explain: '西格玛双引擎同时支持浅压缩（低延迟）和深压缩（低带宽）两种编码方式，可按场景灵活切换。' },
  { id: 'tcz_s13', type: 'single', question: '在LED屏幕方案计算中，发送卡数量由什么决定？', options: ['屏幕总像素和发送卡带载能力', '屏幕面积', '接收卡数量', '网线长度'], answer: 'A', points: 5, explain: '发送卡数量 = 屏幕总像素 / 单卡带载能力（130万像素），需向上取整。' },
  { id: 'tcz_s14', type: 'single', question: '灵曜视频会议系统通过什么协议与第三方系统互通？', options: ['SIP/H.323', 'HTTP', 'FTP', 'SMTP'], answer: 'A', points: 5, explain: '灵曜视频会议通过SIP/H.323标准协议网关与腾讯会议、Zoom等第三方系统互通。' },
  { id: 'tcz_s15', type: 'single', question: '泰山光纤坐席系统的主要传输介质是什么？', options: ['光纤', '网线', '同轴电缆', 'HDMI线'], answer: 'A', points: 5, explain: '泰山光纤坐席基于光纤KVM技术，实现人机分离、超低延迟和高安全性。' },
  { id: 'tcz_s16', type: 'single', question: '音频处理器中压缩器的主要功能是什么？', options: ['控制动态范围，防止信号过载', '增加音量', '改变音色', '消除噪声'], answer: 'A', points: 5, explain: '压缩器通过压缩动态范围，将过大信号降低，防止削波失真，保护扬声器系统。' },
  { id: 'tcz_s17', type: 'single', question: 'LED显示屏的刷新率通常要求达到多少？', options: ['3840Hz以上', '60Hz', '120Hz', '240Hz'], answer: 'A', points: 5, explain: 'LED显示屏刷新率通常要求3840Hz以上，确保拍摄时不出现扫描线。' },
  { id: 'tcz_s18', type: 'single', question: '科赛无纸化会议系统的核心功能是什么？', options: ['会议文件电子化管理、共享和协作', '打印纸质文件', '扫描纸质文件', '销毁文件'], answer: 'A', points: 5, explain: '科赛无纸化会议系统实现会议全流程电子化，包括议程、文件、投票、批注等。' },
  { id: 'tcz_s19', type: 'single', question: 'NVDS解码矩阵的主要应用场景是什么？', options: ['安防监控和指挥中心', '家庭影院', 'KTV', '录音棚'], answer: 'A', points: 5, explain: 'NVDS解码矩阵接收IP网络视频流并解码输出，广泛应用于安防监控和指挥中心。' },
  { id: 'tcz_s20', type: 'single', question: '诺瓦ColorAjust技术的主要作用是什么？', options: ['实现LED屏幕的逐点色彩校正', '调节屏幕亮度', '调整画面比例', '优化网络传输'], answer: 'A', points: 5, explain: 'ColorAjust是诺瓦的逐点色彩校正技术，通过对每个像素点独立校准，消除色差和亮度不均。' },
  { id: 'tcz_s21', type: 'single', question: '全网口极简方案的核心设计理念是什么？', options: ['用一根网线统一传输所有信号', '使用无线传输', '使用光纤传输', '使用同轴电缆'], answer: 'A', points: 5, explain: '全网口极简方案统一使用网线传输音视频、控制、网络和供电，实现一线通。' },
  { id: 'tcz_s22', type: 'single', question: '奥菲斯系列音频产品的核心特点是什么？', options: ['支持Dante网络音频的高端数字处理', '入门级模拟音频', '仅支持蓝牙', '不需要供电'], answer: 'A', points: 5, explain: '奥菲斯系列是高端数字音频处理产品，支持Dante网络音频协议。' },
  { id: 'tcz_s23', type: 'single', question: '磐石管控系统在分布式系统中的角色是什么？', options: ['统一管理监控所有分布式节点', '播放视频内容', '处理音频信号', '控制灯光'], answer: 'A', points: 5, explain: '磐石管控系统提供分布式节点的统一管理、状态监控、配置下发和固件升级功能。' },
  { id: 'tcz_s24', type: 'single', question: '阿尔法专业拼控支持的最大输出分辨率是多少？', options: ['8K及以上', '1080P', '2K', '4K'], answer: 'A', points: 5, explain: '阿尔法专业拼控支持8K及以上分辨率输出，满足超大型LED屏幕需求。' },
  { id: 'tcz_s25', type: 'single', question: 'LED屏幕灰度等级通常用多少bit表示？', options: ['14bit', '8bit', '10bit', '12bit'], answer: 'A', points: 5, explain: 'LED显示系统通常使用14bit灰度处理，可呈现16384级灰度，确保画面细腻。' },
  { id: 'tcz_s26', type: 'single', question: '灵石可视化系统的主要功能是什么？', options: ['音视频信号的可视化调度和管理', '生成3D动画', '编辑视频', '制作PPT'], answer: 'A', points: 5, explain: '灵石可视化系统提供图形化的音视频信号调度界面，通过拖拽实现信号路由和切换。' },
  { id: 'tcz_s27', type: 'single', question: 'EG系列播控终端的部署方式是什么？', options: ['部署在显示终端附近，通过网络接收指令', '部署在云端', '部署在手机中', '不需要部署硬件'], answer: 'A', points: 5, explain: 'EG系列播控终端部署在显示终端附近，连接屏幕，通过网络接收服务器指令和内容。' },
  { id: 'tcz_s28', type: 'single', question: '公共广播系统中，定压输出的标准电压是多少？', options: ['70V或100V', '12V', '24V', '220V'], answer: 'A', points: 5, explain: '公共广播系统采用70V或100V定压输出，适合远距离多扬声器并联连接。' },
  { id: 'tcz_s29', type: 'single', question: '在方案设计中，电源功率通常按总功耗的多少比例选择？', options: ['125%（80%负载率）', '100%', '90%', '150%'], answer: 'A', points: 5, explain: '电源选型按80%负载率计算，即选用额定功率为总功耗1.25倍以上的电源，留有安全余量。' },
  { id: 'tcz_s30', type: 'single', question: '诺瓦GTS/屏老板系统属于什么类型的产品？', options: ['LED屏幕远程管理平台', 'LED屏幕硬件', '视频播放软件', '屏幕校准工具'], answer: 'A', points: 5, explain: 'GTS和屏老板是诺瓦的LED屏幕远程管理平台，提供设备监控、内容发布和故障告警等功能。' },

  // ===== 多选题 (5题/套，题库~15题) =====
  { id: 'tcz_m1', type: 'multiple', question: '以下哪些属于诺瓦品牌的产品线？', options: ['LED控制系统', '视频拼接处理器', 'LED一体机', '配件产品', 'GTS远程管理平台'], answer: 'ABCDE', points: 5, explain: '诺瓦产品线涵盖LED控制系统、视频处理器、LED一体机、配件和GTS管理平台。' },
  { id: 'tcz_m2', type: 'multiple', question: '以下哪些属于嗨动品牌的产品线？', options: ['B系列拼接处理器', '天韵音频系统', '易诚分布式', '缪斯播控', '灵曜视频会议'], answer: 'ABCDE', points: 5, explain: '嗨动产品线覆盖视频拼接、音频扩声、分布式、播控和视频会议等领域。' },
  { id: 'tcz_m3', type: 'multiple', question: '以下哪些是LED显示屏的重要性能指标？', options: ['刷新率', '灰度等级', '像素间距', '亮度', '对比度'], answer: 'ABCDE', points: 5, explain: '刷新率、灰度等级、像素间距、亮度和对比度是衡量LED显示屏性能的关键指标。' },
  { id: 'tcz_m4', type: 'multiple', question: '分布式系统相比传统矩阵切换器有哪些优势？', options: ['扩展灵活', '布线简单', '远距离传输', '单点故障不影响整体', '维护成本低'], answer: 'ABCDE', points: 5, explain: '分布式系统具有扩展灵活、布线简单、远距离传输、故障隔离和维护成本低等优势。' },
  { id: 'tcz_m5', type: 'multiple', question: '专业音频系统中常见的接口类型有哪些？', options: ['XLR（卡侬）', 'TRS 6.35mm', 'Speakon', 'RCA', 'Dante网络接口'], answer: 'ABCDE', points: 5, explain: 'XLR、TRS、Speakon、RCA和Dante网络接口都是专业音频系统中常见的接口类型。' },
  { id: 'tcz_m6', type: 'multiple', question: '以下哪些场景适合使用视频拼接处理器？', options: ['大型LED屏幕', '会议室多屏', '演播室', '监控中心', '指挥中心'], answer: 'ABCDE', points: 5, explain: '视频拼接处理器广泛应用于LED大屏、会议室、演播室、监控中心和指挥中心等场景。' },
  { id: 'tcz_m7', type: 'multiple', question: '诺瓦LED一体机支持哪些信号输入方式？', options: ['HDMI', '无线投屏', 'USB播放', 'Type-C', '网络流媒体'], answer: 'ABCDE', points: 5, explain: 'LED一体机支持HDMI、无线投屏、USB、Type-C和网络流媒体等多种信号输入。' },
  { id: 'tcz_m8', type: 'multiple', question: '以下哪些是嗨动中控系统的产品？', options: ['ECS3000', '艾欧塔中控', '灵石可视化', '磐石管控', '全网口极简方案'], answer: 'ABCDE', points: 5, explain: '嗨动中控产品线包括ECS3000、艾欧塔、灵石、磐石和全网口极简方案等。' },
  { id: 'tcz_m9', type: 'multiple', question: 'LED屏幕出现画面异常时，可能的原因包括哪些？', options: ['信号线接触不良', '接收卡配置错误', '电源供电不足', '网线质量差', '固件版本过旧'], answer: 'ABCDE', points: 5, explain: '画面异常可能由信号线、接收卡配置、电源、网线和固件等多种原因导致。' },
  { id: 'tcz_m10', type: 'multiple', question: '音频系统中的啸叫可能由哪些原因引起？', options: ['麦克风与扬声器距离过近', '系统增益过高', '房间反射强烈', 'EQ设置不当', '麦克风指向性不合适'], answer: 'ABCDE', points: 5, explain: '啸叫可能由麦克风拾取扬声器声音、增益过高、房间反射、EQ设置和指向性等多种原因导致。' },
  { id: 'tcz_m11', type: 'multiple', question: '缪斯播控系统支持哪些播放方式？', options: ['定时播放', '即时插播', '循环播放', '多区域同步', 'LED屏专用播放'], answer: 'ABCDE', points: 5, explain: '缪斯系统支持定时、即时插播、循环、多区域同步和LED屏专用播放等多种方式。' },
  { id: 'tcz_m12', type: 'multiple', question: '以下哪些因素影响LED屏幕方案的总体成本？', options: ['像素间距', '屏幕面积', '控制系统规格', '安装方式', '配件选择'], answer: 'ABCDE', points: 5, explain: '像素间距、面积、控制系统规格、安装方式和配件选择都会影响总体方案成本。' },
  { id: 'tcz_m13', type: 'multiple', question: '灵曜视频会议系统支持哪些协作功能？', options: ['屏幕共享', '电子白板', '文件共享', '会议录制', '多方视频'], answer: 'ABCDE', points: 5, explain: '灵曜系统支持屏幕共享、电子白板、文件共享、会议录制和多方视频等协作功能。' },
  { id: 'tcz_m14', type: 'multiple', question: '西格玛双引擎分布式系统的两种编码模式分别适用于什么场景？', options: ['浅压缩适合本地坐席协作', '深压缩适合远程传输', '浅压缩适合低延迟操作', '深压缩适合低带宽环境', '两种模式可混合使用'], answer: 'ABCDE', points: 5, explain: '浅压缩适合本地坐席和低延迟操作，深压缩适合远程传输和低带宽环境，两种模式可混合使用。' },
  { id: 'tcz_m15', type: 'multiple', question: '在综合项目中，如何实现多个子系统的统一管理？', options: ['统一管理平台', '标准化接口协议', '场景联动', '统一权限管理', '协同运维监控'], answer: 'ABCDE', points: 5, explain: '通过统一平台、标准接口、场景联动、统一权限和协同运维实现多系统统一管理。' },

  // ===== 判断题 (5题/套，题库~15题) =====
  { id: 'tcz_j1', type: 'judge', question: '诺瓦和嗨动是同一家公司旗下的两个品牌。', options: ['正确', '错误'], answer: 'B', points: 5, explain: '诺瓦(NovaStar)和嗨动(Hidong)是两个独立的品牌，各自拥有不同的产品线和市场定位。' },
  { id: 'tcz_j2', type: 'judge', question: 'LED显示屏的刷新率越高，拍摄时越不容易出现扫描线。', options: ['正确', '错误'], answer: 'A', points: 5, explain: '刷新率越高，LED屏幕在一帧内刷新次数越多，相机拍摄时越不容易出现扫描线。' },
  { id: 'tcz_j3', type: 'judge', question: '分布式系统中，编码器和解码器必须按1:1比例配置。', options: ['正确', '错误'], answer: 'B', points: 5, explain: '分布式系统中编码器和解码器按实际需求灵活配置，一个编码器可被多个解码器调用。' },
  { id: 'tcz_j4', type: 'judge', question: 'XLR平衡传输的抗干扰能力优于RCA非平衡传输。', options: ['正确', '错误'], answer: 'A', points: 5, explain: 'XLR平衡传输利用共模抑制原理消除干扰，传输距离和抗干扰能力远优于非平衡RCA。' },
  { id: 'tcz_j5', type: 'judge', question: 'LED一体机需要额外配置发送卡和接收卡才能使用。', options: ['正确', '错误'], answer: 'B', points: 5, explain: 'LED一体机将发送卡和接收卡集成在内部，开箱即用，无需额外配置。' },
  { id: 'tcz_j6', type: 'judge', question: 'Dante音频系统必须使用专用的音频交换机。', options: ['正确', '错误'], answer: 'B', points: 5, explain: 'Dante可使用标准网络交换机，但推荐使用支持QoS和IGMP Snooping的交换机以保证音频质量。' },
  { id: 'tcz_j7', type: 'judge', question: '无缝混插矩阵可以实现信号切换时零黑屏。', options: ['正确', '错误'], answer: 'A', points: 5, explain: '无缝混插矩阵采用帧同步技术，实现信号切换时无黑屏、无闪烁的平滑过渡。' },
  { id: 'tcz_j8', type: 'judge', question: '公共广播系统的定压功放可以直接连接定阻扬声器。', options: ['正确', '错误'], answer: 'B', points: 5, explain: '定压功放和定阻扬声器不能直接连接，需要通过变压器匹配，否则会损坏设备。' },
  { id: 'tcz_j9', type: 'judge', question: '阿丽塔LED拼控集成了发送卡和接收卡的功能。', options: ['正确', '错误'], answer: 'A', points: 5, explain: '阿丽塔LED拼控将发送卡和接收卡功能集成，直接驱动LED模组，简化系统架构。' },
  { id: 'tcz_j10', type: 'judge', question: '任何分辨率的视频源都可以直接接入LED发送卡。', options: ['正确', '错误'], answer: 'B', points: 5, explain: '发送卡有最大输入分辨率限制，超过限制的视频源需要先通过视频处理器进行缩放处理。' },
  { id: 'tcz_j11', type: 'judge', question: '光纤传输相比网线传输具有更远的传输距离和更强的抗干扰能力。', options: ['正确', '错误'], answer: 'A', points: 5, explain: '光纤传输距离可达数十公里，且不受电磁干扰，是长距离信号传输的最佳选择。' },
  { id: 'tcz_j12', type: 'judge', question: '音视频处理器可以完全替代调音台的所有功能。', options: ['正确', '错误'], answer: 'B', points: 5, explain: '音频处理器和调音台功能不同：处理器用于信号优化，调音台用于多路混合和实时控制，两者互补。' },
  { id: 'tcz_j13', type: 'judge', question: '缪斯播控系统支持多区域内容的独立播放。', options: ['正确', '错误'], answer: 'A', points: 5, explain: '缪斯播控系统支持多区域独立管理，不同显示终端可播放不同内容。' },
  { id: 'tcz_j14', type: 'judge', question: '在方案计算中，发送卡数量只与屏幕面积有关。', options: ['正确', '错误'], answer: 'B', points: 5, explain: '发送卡数量由屏幕总像素点决定，而非面积。相同面积下不同像素间距的屏幕像素点数差异很大。' },
  { id: 'tcz_j15', type: 'judge', question: 'LED屏幕的逐点校正可以消除色差和亮度不均。', options: ['正确', '错误'], answer: 'A', points: 5, explain: '逐点校正技术通过对每个像素点的独立校准，有效消除色差和亮度不均，提升整体画质。' },

  // ===== 简答题 (4题/套，题库~10题) =====
  { id: 'tcz_q1', type: 'short', question: '在一个综合性的指挥中心项目中，需要集成LED大屏显示、视频拼接处理、分布式系统、音频扩声和中控系统。请简述各子系统的功能定位和相互之间的关系。', keywords: 'LED,显示,拼接,分布式,音频,中控,集成,联动,统一,管理', points: 10, explain: 'LED大屏负责最终显示；视频拼接处理负责多信号接入和画面布局；分布式系统负责信号远距离传输调度；音频扩声负责声音覆盖；中控系统作为统一管理平台，实现各子系统的场景联动和集中控制。' },
  { id: 'tcz_q2', type: 'short', question: '请对比分析诺瓦LED控制系统和嗨动阿丽塔LED拼控在系统架构上的差异，并说明各自的适用场景。', keywords: '诺瓦,发送卡,接收卡,阿丽塔,集成,架构,场景,一体机', points: 10, explain: '诺瓦方案：发送卡+接收卡分离架构，灵活配置，适合大型和复杂项目。阿丽塔方案：集成架构，直接驱动模组，适合一体机和中小型标准化项目。差异在于灵活性和集成度。' },
  { id: 'tcz_q3', type: 'short', question: '在为客户设计一个多功能报告厅方案时，需要整合哪些子系统？请列出并说明各子系统的关键考虑因素。', keywords: '显示,音频,中控,视频会议,灯光,布线,场景,联动', points: 10, explain: '子系统：1.显示系统（LED/LCD选型）；2.音频扩声（声场覆盖）；3.中控系统（设备统一控制）；4.视频会议（远程协作）；5.灯光系统（场景照明）；6.信号管理系统（布线方案）。关键考虑：场景联动和用户体验。' },
  { id: 'tcz_q4', type: 'short', question: '请说明分布式系统和传统矩阵切换器在大型项目中的选型决策依据。', keywords: '规模,距离,扩展,布线,成本,维护,灵活,网络', points: 10, explain: '选型依据：1.项目规模（节点数量）；2.传输距离（远距离选分布式）；3.扩展需求（频繁扩展选分布式）；4.布线条件（已有网络选分布式）；5.维护需求（分布式更易维护）；6.预算考量。' },
  { id: 'tcz_q5', type: 'short', question: 'LED屏幕出现"黑屏"故障时，应该如何从控制系统、电源、信号源三个维度进行系统排查？', keywords: '黑屏,电源,发送卡,接收卡,网线,信号源,配置,排查', points: 10, explain: '排查顺序：1.电源维度：检查主电源、模组电源、接收卡供电；2.信号源维度：检查信号源输出、发送卡指示灯、输入信号线缆；3.控制维度：检查接收卡状态、网线连接、配置文件、固件版本。' },
  { id: 'tcz_q6', type: 'short', question: '在大型演出活动中，如何确保视频切换和音频扩声两个系统的同步协作？', keywords: '同步,延迟,声画,Genlock,时钟,测试,预案,彩排', points: 10, explain: '确保同步：1.使用Genlock同步锁相确保视频帧同步；2.音频系统配置延迟补偿；3.全系统联调测试声画同步；4.制定应急预案；5.多次彩排验证；6.专业技术保障团队现场值守。' },
  { id: 'tcz_q7', type: 'short', question: '请从产品兼容性角度，分析诺瓦和嗨动产品在同一个项目中协同工作的可能性和注意事项。', keywords: '兼容,接口,协议,标准,集成,中控,信号,协同', points: 10, explain: '协同可能性：1.基于标准接口（HDMI/DVI/SDI）的信号互通；2.通过中控系统统一管理；3.注意事项：确认接口协议兼容性、分辨率匹配、控制协议统一、信号格式一致。建议使用统一中控平台实现协同。' },
  { id: 'tcz_q8', type: 'short', question: '在智慧城市项目中，如何实现LED大屏、播控系统和分布式系统的三层架构协同工作？', keywords: '播控,LED,分布式,内容,管理,调度,显示,协同', points: 10, explain: '三层架构：1.播控层（缪斯）负责内容管理和播放计划；2.分布层（易诚/西格玛）负责信号调度和传输；3.显示层（LED大屏）负责最终呈现。通过统一管理平台实现三层协同，内容从播控到分布式再到LED的无缝流转。' },
  { id: 'tcz_q9', type: 'short', question: '一个完整的会议室解决方案包含哪些核心子系统？请从诺瓦和嗨动产品线中为每个子系统推荐合适的产品。', keywords: '显示,音频,中控,视频会议,信号,分布式,产品,推荐', points: 10, explain: '核心子系统：1.显示：诺瓦LED一体机或嗨动LCD拼接；2.音频：嗨动天韵系列扩声；3.中控：嗨动ECS3000或艾欧塔；4.视频会议：嗨动灵曜系统；5.信号管理：嗨动分布式或全网口极简方案。根据预算和规模选择对应产品级别。' },
  { id: 'tcz_q10', type: 'short', question: '在为客户提供技术方案时，如何根据客户的预算和需求，在诺瓦和嗨动产品之间进行合理的产品组合推荐？', keywords: '预算,需求,场景,阶梯,推荐,组合,方案,定位', points: 10, explain: '推荐策略：1.明确客户核心需求和预算范围；2.根据场景规模划分产品级别（入门/中端/高端）；3.核心系统（LED/显示）按需选择诺瓦或嗨动；4.配套系统（音频/中控/分布式）选择嗨动产品；5.提供多套阶梯方案供客户选择。' },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = QUESTIONS_tech_comprehensive;
}